version: '2'

volumes:
  db-data:
    external: false
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db-data:/var/lib/postgresql/db-data

  web:
    tty: true
    stdin_open: true
    build: .
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app