FROM ruby:2.6.5

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ADD Gemfile* $APP_HOME/
RUN gem install bundler:2.1.4
RUN bundle install

ADD . $APP_HOME

EXPOSE 8080

ENTRYPOINT ["sh", "bin/entrypoint"]