version: '2'
services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    tty: true
    stdin_open: true
    build: .
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app