version: '2'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    tty: true
    stdin_open: true
    build: .
    entrypoint: [bin/entry]
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app