development:
  adapter: postgresql
  database: app_development
  pool: 5
  username: postgres
  host: db

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  username: sample_postgres
  password: